import { ruleSetSchema, type ClassificationOption, type RuleSet } from '@sheetpilot/core';

export const ACCOUNT_FAULT_TAXONOMY: ClassificationOption[] = [
  {
    code: 'POWER_LOSS',
    label: 'Power Loss',
    category: 'Power',
    description: 'Mains power absent or unstable at the site.',
  },
  {
    code: 'BATTERY_DEGRADED',
    label: 'Battery Degraded',
    category: 'Power',
    description: 'Backup battery below capacity or failing self-test.',
  },
  {
    code: 'CONNECTIVITY_FAILURE',
    label: 'Connectivity Failure',
    category: 'Communications',
    description: 'Device unreachable or reporting communication faults.',
  },
  {
    code: 'SENSOR_FAULT',
    label: 'Sensor Fault',
    category: 'Hardware',
    description: 'Sensor or probe reporting invalid readings.',
  },
  {
    code: 'TAMPER_DETECTED',
    label: 'Tamper Detected',
    category: 'Security',
    description: 'Enclosure or line tamper indication.',
  },
  {
    code: 'TRANSIENT_FAULT',
    label: 'Transient Fault',
    category: 'Software',
    description: 'Self-cleared fault after reset with no recurring history.',
  },
  {
    code: 'UNSPECIFIED_FAULT',
    label: 'Unspecified Fault',
    category: 'Unknown',
    description: 'Fault reported without a recognised signature.',
  },
];

export const DEFAULT_ACCOUNT_FAULT_RULE_SET: RuleSet = ruleSetSchema.parse({
  slug: 'account-fault-triage-default',
  workflowSlug: 'account-fault-triage',
  name: 'Account fault triage (default)',
  version: 1,
  active: true,
  rules: [
    {
      id: 'tamper-detected',
      name: 'Tamper detected',
      description: 'Tamper indications are treated as security incidents.',
      priority: 100,
      when: {
        mode: 'any',
        conditions: [
          { field: 'description', operator: 'contains', value: 'tamper' },
          { field: 'description', operator: 'contains', value: 'case open' },
        ],
      },
      then: [
        { field: 'RootCause', value: 'Tamper Detected' },
        { field: 'FaultCategory', value: 'Security' },
        { field: 'RecommendedAction', value: 'Dispatch security inspection' },
        { field: 'Priority', value: 'P1' },
      ],
      confidence: 0.97,
      explanationTemplate: 'Detected tamper signature "{matchedTerm}" -> security incident.',
      tags: ['security'],
    },
    {
      id: 'power-loss',
      name: 'Power loss',
      description: 'Mains power failures.',
      priority: 95,
      when: {
        mode: 'any',
        conditions: [
          { field: 'description', operator: 'contains', value: 'no power' },
          { field: 'description', operator: 'contains', value: 'power fail' },
          { field: 'description', operator: 'contains', value: 'power loss' },
          { field: 'description', operator: 'contains', value: 'mains fail' },
          { field: 'description', operator: 'matches_regex', value: 'power\\s+(lost|outage)' },
        ],
      },
      then: [
        { field: 'RootCause', value: 'Power Loss' },
        { field: 'FaultCategory', value: 'Power' },
        { field: 'RecommendedAction', value: 'Verify supply and dispatch technician' },
        { field: 'Priority', value: 'P2' },
      ],
      confidence: 0.95,
      explanationTemplate: 'Term "{matchedTerm}" indicates mains power loss.',
      tags: ['power'],
    },
    {
      id: 'battery-degraded',
      name: 'Battery degraded',
      description: 'Battery capacity or self-test failures.',
      priority: 90,
      when: {
        mode: 'any',
        conditions: [
          { field: 'description', operator: 'contains', value: 'battery low' },
          { field: 'description', operator: 'contains', value: 'low battery' },
          { field: 'description', operator: 'contains', value: 'battery fail' },
          { field: 'description', operator: 'contains', value: 'battery degraded' },
          { field: 'description', operator: 'contains', value: 'batt low' },
        ],
      },
      then: [
        { field: 'RootCause', value: 'Battery Degraded' },
        { field: 'FaultCategory', value: 'Power' },
        { field: 'RecommendedAction', value: 'Schedule battery replacement' },
        { field: 'Priority', value: 'P3' },
      ],
      confidence: 0.92,
      explanationTemplate: 'Term "{matchedTerm}" indicates a degraded backup battery.',
      tags: ['power', 'battery'],
    },
    {
      id: 'connectivity-failure',
      name: 'Connectivity failure',
      description: 'Device offline or unable to communicate.',
      priority: 85,
      when: {
        mode: 'any',
        conditions: [
          { field: 'description', operator: 'contains', value: 'no signal' },
          { field: 'description', operator: 'contains', value: 'offline' },
          { field: 'description', operator: 'contains', value: 'no comms' },
          { field: 'description', operator: 'contains', value: 'comms fail' },
          { field: 'description', operator: 'contains', value: 'communication fail' },
          { field: 'description', operator: 'contains', value: 'network loss' },
        ],
      },
      then: [
        { field: 'RootCause', value: 'Connectivity Failure' },
        { field: 'FaultCategory', value: 'Communications' },
        { field: 'RecommendedAction', value: 'Check connectivity and signal strength' },
        { field: 'Priority', value: 'P2' },
      ],
      confidence: 0.9,
      explanationTemplate: 'Term "{matchedTerm}" indicates a connectivity failure.',
      tags: ['comms'],
    },
    {
      id: 'sensor-fault',
      name: 'Sensor fault',
      description: 'Sensor or probe faults.',
      priority: 80,
      when: {
        mode: 'any',
        conditions: [
          { field: 'description', operator: 'contains', value: 'sensor fault' },
          { field: 'description', operator: 'contains', value: 'sensor error' },
          { field: 'description', operator: 'contains', value: 'sensor fail' },
          { field: 'description', operator: 'contains', value: 'probe fault' },
          { field: 'description', operator: 'matches_regex', value: 'invalid\\s+reading' },
        ],
      },
      then: [
        { field: 'RootCause', value: 'Sensor Fault' },
        { field: 'FaultCategory', value: 'Hardware' },
        { field: 'RecommendedAction', value: 'Replace or recalibrate sensor' },
        { field: 'Priority', value: 'P3' },
      ],
      confidence: 0.88,
      explanationTemplate: 'Term "{matchedTerm}" indicates a sensor or probe fault.',
      tags: ['hardware'],
    },
    {
      id: 'transient-reset',
      name: 'Transient fault after reset',
      description: 'Single reset with no repeated occurrence.',
      priority: 70,
      when: {
        mode: 'all',
        conditions: [
          { field: 'description', operator: 'contains', value: 'reset' },
          { field: 'faultCount', operator: 'lte', value: 1 },
        ],
      },
      then: [
        { field: 'RootCause', value: 'Transient Fault' },
        { field: 'FaultCategory', value: 'Software' },
        { field: 'RecommendedAction', value: 'Monitor for recurrence' },
        { field: 'Priority', value: 'P4' },
      ],
      confidence: 0.8,
      explanationTemplate: 'Single reset event ("{matchedTerm}") treated as transient.',
      tags: ['software'],
    },
    {
      id: 'generic-fault',
      name: 'Generic fault wording',
      description: 'Catch-all for recognised fault wording without a specific signature.',
      priority: 10,
      when: {
        mode: 'any',
        conditions: [
          { field: 'description', operator: 'contains', value: 'fault' },
          { field: 'description', operator: 'contains', value: 'error' },
          { field: 'description', operator: 'contains', value: 'alarm' },
        ],
      },
      then: [
        { field: 'RootCause', value: 'Unspecified Fault' },
        { field: 'FaultCategory', value: 'Unknown' },
        { field: 'RecommendedAction', value: 'Manual triage required' },
        { field: 'Priority', value: 'P4' },
      ],
      confidence: 0.6,
      explanationTemplate: 'Generic fault wording "{matchedTerm}" requires manual triage.',
      tags: ['fallback'],
    },
  ],
});
